name: "Hotfix Action"
description: Github Action that will handle a hotfix in the Release Flow."
inputs:
  github-token:
    description: "Default Github token"
    required: true
  workflow-token:
    description: "Personal access token"
    required: true
  slack-webhook-url:
    description: "URL to send Slack webhooks to"
    required: true
  tag:
    description: "Tag to apply the hotfix for"
    required: true
runs:
  using: "node16"
  main: "index.js"
